# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit configuration for mcp-for-argo-workflows
# Docs: https://docs.coderabbit.ai/getting-started/yaml-configuration

language: "en-US"
early_access: false

reviews:
  # Use assertive profile for strict, thorough reviews
  profile: "assertive"

  # Request changes workflow - auto-approve when comments are resolved
  request_changes_workflow: true

  # Review output options
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false

  # Automatic review settings
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false

  # Path-based filtering
  path_filters:
    - "!.claude/**"
    - "!**/*.md"

  # Path-specific review instructions
  path_instructions:
    - path: "**/*.go"
      instructions: |
        Review Go code for:
        - Proper error handling (no ignored errors)
        - Correct use of context.Context
        - Resource cleanup (defer for Close, etc.)
        - Thread safety and race conditions
        - Adherence to Go idioms and best practices
        - Proper use of interfaces
    - path: "internal/tools/**"
      instructions: |
        This directory contains MCP tool implementations. Review for:
        - Correct JSON schema definitions
        - Proper input validation
        - Clear error messages for users
        - Consistent tool naming conventions
    - path: "internal/argo/**"
      instructions: |
        This directory contains Argo Workflows client code. Review for:
        - Correct use of Argo client APIs
        - Proper handling of Kubernetes errors
        - Namespace handling
        - Connection mode compatibility (direct K8s vs Argo Server)

chat:
  auto_reply: true

# Knowledge base for additional context
knowledge_base:
  opt_out: false
  learnings:
    scope: "auto"
